### ISSUE TITLE
[refactor] Clean up checklist for initial public release

### ISSUE THREAD

**Issue by parasj** [parasj/checkmate#17]
# Done
- [x] Add citation block
- [x] Rename repo to checkmate
- [x] Rename references to `remat` to `checkmate`
- [x] Modify python package name and directory structure to `checkmate`
- [x] Clean up black/pylint issues #82 
- [x] Add license #80 
- [x] Documentation #83

# Marketing
- [x] Logo
- [x] Website (Idea could be ramcheckmate.com)
- [ ] Social media banner logo for GitHub
- [ ] Write a short tutorial for how to use checkmate on your own models
- [ ] Publish to PyPI
